### ISSUE TITLE
SH.hpp error while compiling on windows. 

### ISSUE THREAD

**Issue by PaoloBenigni** [jparkhill/TensorMol#26]
So I am trying to install this on windows, and I'm getting an odd error in SH.hpp that seems to be killing the installation.  Here is the output code. 

> Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Obtaining file:///C:/Users/hi/Desktop/git/tensormol
  Running setup.py (path:C:\Users\hi\Desktop\git\tensormol\setup.py) egg_info for package from file:///C:/Users/hi/Desktop/git/tensormol
    Running command python setup.py egg_info
    Numpy Include Dir:  c:\python36\lib\site-packages\numpy\core\include
    running egg_info
    writing TensorMol.egg-info\PKG-INFO
    writing dependency_links to TensorMol.egg-info\dependency_links.txt
    writing top-level names to TensorMol.egg-info\top_level.txt
    reading manifest file 'TensorMol.egg-info\SOURCES.txt'
    writing manifest file 'TensorMol.egg-info\SOURCES.txt'
  Source in c:\users\hi\desktop\git\tensormol has version 0.2, which satisfies requirement TensorMol==0.2 from file:///C:/Users/hi/Desktop/git/tensormol
Installing collected packages: TensorMol
  Running setup.py develop for TensorMol
    Running command c:\python36\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\hi\\Desktop\\git\\tensormol\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    Numpy Include Dir:  c:\python36\lib\site-packages\numpy\core\include
    running develop
    running egg_info
    writing TensorMol.egg-info\PKG-INFO
    writing dependency_links to TensorMol.egg-info\dependency_links.txt
    writing top-level names to TensorMol.egg-info\top_level.txt
    reading manifest file 'TensorMol.egg-info\SOURCES.txt'
    writing manifest file 'TensorMol.egg-info\SOURCES.txt'
    running build_ext
    building 'MolEmb' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python36\lib\site-packages\numpy\core\include -I./C_API/ -Ic:\python36\include -Ic:\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /EHsc /Tp./C_API/MolEmb.cpp /Fobuild\temp.win-amd64-3.6\Release\./C_API/MolEmb.obj -g -openmp -w
    **cl : Command line warning D9025 : overriding '/W3' with '/w'
    cl : Command line warning D9002 : ignoring unknown option '-g'
    MolEmb.cpp
    c:\python36\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(850): error C2131: expression did not evaluate to a constant
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(850): note: failure was caused by a read of a variable outside its lifetime
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(850): note: see usage of 'Prm'
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(851): error C2131: expression did not evaluate to a constant
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(851): note: failure was caused by a read of a variable outside its lifetime
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(851): note: see usage of 'Prm'
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(852): error C2131: expression did not evaluate to a constant
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(852): note: failure was caused by a read of a variable outside its lifetime
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(852): note: see usage of 'Prm'
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(853): error C2131: expression did not evaluate to a constant
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(853): note: failure was caused by a read of a variable outside its lifetime
    c:\users\hi\desktop\git\tensormol\c_api\SH.hpp(853): note: see usage of 'Prm'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2**
Cleaning up...
Command "c:\python36\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\hi\\Desktop\\git\\tensormol\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\hi\Desktop\git\tensormol\
Exception information:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python36\lib\site-packages\pip\req\req_install.py", line 845, in install
    install_options, global_options, prefix=prefix)
  File "c:\python36\lib\site-packages\pip\req\req_install.py", line 1007, in install_editable
    show_stdout=False)
  File "c:\python36\lib\site-packages\pip\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "c:\python36\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\hi\\Desktop\\git\\tensormol\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\hi\Desktop\git\tensormol\

There are a few thing to change in the compiling arguments, but Im not quite sure why the error in SH.hpp comes out. Any thoughts?

**Comment by jparkhill** [comment]
In our experience the windows POSIX extensions are a semi-functional nightmare, and we have no plans to support Win... Actually even getting TF working on windows was awful the last time we tried. That said: these routines in SH.hpp aren't really used in the code you would be interested in using. Actually we've since re-written them in Tensorflow. 

I think you should try basically commenting out the function bodies. I think that should work for your purposes.

**Comment by PaoloBenigni** [comment]
So it doesnt seem to be so straight forward. Other parts of  MolEmb.cpp start falling apart. A few or to || conversions fixed some of it, but there are still other problems im trying to sort out. 

```
 ./C_API/MolEmb.cpp(820): error C2131: expression did not evaluate to a constant
    ./C_API/MolEmb.cpp(820): note: failure was caused by a read of a variable outside its lifetime
    ./C_API/MolEmb.cpp(820): note: see usage of 'natom'
    ./C_API/MolEmb.cpp(832): error C3863: array type 'double [natom][3]' is not assignable
    ./C_API/MolEmb.cpp(833): error C3863: array type 'double [natom][3]' is not assignable
    ./C_API/MolEmb.cpp(834): error C3863: array type 'double [natom][3]' is not assignable
    ./C_API/MolEmb.cpp(1265): error C2131: expression did not evaluate to a constant
    ./C_API/MolEmb.cpp(1265): note: failure was caused by a read of a variable outside its lifetime
    ./C_API/MolEmb.cpp(1265): note: see usage of 'xyz'
    ./C_API/MolEmb.cpp(1309): error C2131: expression did not evaluate to a constant
    ./C_API/MolEmb.cpp(1265): note: failure was caused by a read of a variable outside its lifetime
    ./C_API/MolEmb.cpp(1265): note: see usage of 'xyz'
    ./C_API/MolEmb.cpp(1336): error C3863: array type 'int [nx]' is not assignable
    ./C_API/MolEmb.cpp(1414): error C2131: expression did not evaluate to a constant
    ./C_API/MolEmb.cpp(1414): note: failure was caused by a read of a variable outside its lifetime
    ./C_API/MolEmb.cpp(1414): note: see usage of 'dmat1'
    ./C_API/MolEmb.cpp(1417): error C2131: expression did not evaluate to a constant
    ./C_API/MolEmb.cpp(1414): note: failure was caused by a read of a variable outside its lifetime
    ./C_API/MolEmb.cpp(1414): note: see usage of 'dmat1'
    ./C_API/MolEmb.cpp(2063): error C2131: expression did not evaluate to a constant
    ./C_API/MolEmb.cpp(2063): note: failure was caused by a read of a variable outside its lifetime
    ./C_API/MolEmb.cpp(2063): note: see usage of 'dim_zeta'
    ./C_API/MolEmb.cpp(2089): error C3863: array type 'double [dim_zeta]' is not assignable
    ./C_API/MolEmb.cpp(2092): error C3863: array type 'double [dim_eta1]' is not assignable
    ./C_API/MolEmb.cpp(2094): error C3863: array type 'double [dim_eta2]' is not assignable
    ./C_API/MolEmb.cpp(2096): error C3863: array type 'double [dim_Rs]' is not assignable

```

**Comment by jordangarside** [comment]
@PaoloBenigni I recommend using Bash on Ubuntu on Windows if you really want to keep using windows. It's pretty easy to install and should make your life a lot easier.

[Install directions](https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10)

Someone even has a [gist on installing Tensorflow](https://gist.github.com/digvijayky/e2f91af603b83396d6b3f2d281bb97a7) to it.
