### ISSUE TITLE
Cant figure out how to get TensorMol to work. (GOMP_4.0 not found?)

### ISSUE THREAD

**Issue by xuwenshuo** [jparkhill/TensorMol#41]
Hi, I was trying to get TensorMol to work but i can't seem to figure out why. I followed the instructions and tried to run the sample script "python3 test_tensormol01.py" but i seem to get the error message below. Might someone here be able to enlighten me.

```
Searching for Installed Optional Packages...
MolEmb is not installed. Please cd C_API; sudo python setup.py install /home/red/.local/lib/python3.6/site-packages/pyscf/lib/libgomp.so.1: version GOMP_4.0 not found (required by /home/red/Documents/Structural_Biology/Molecular_Dynamics/TensorMol/MolEmb.cpython-36m-x86_64-linux-gnu.so)

Traceback (most recent call last):
  File "test_tensormol01.py", line 3, in <module>
    from TensorMol import *
  File "/home/red/Documents/Structural_Biology/Molecular_Dynamics/TensorMol/TensorMol/__init__.py", line 28, in <module>
    from .Containers import *
  File "/home/red/Documents/Structural_Biology/Molecular_Dynamics/TensorMol/TensorMol/Containers/__init__.py", line 4, in <module>
    from .Mol import *
  File "/home/red/Documents/Structural_Biology/Molecular_Dynamics/TensorMol/TensorMol/Containers/Mol.py", line 5, in <module>
    import MolEmb
ImportError: /home/red/.local/lib/python3.6/site-packages/pyscf/lib/libgomp.so.1: version GOMP_4.0 not found (required by /home/red/Documents/Structural_Biology/Molecular_Dynamics/TensorMol/MolEmb.cpython-36m-x86_64-linux-gnu.so)
=======    Accumulated Time Information    =======
Category   |||   Time Per Call   |||   Total Elapsed     
Total Time : 0.00290 s
~ Adios Homeshake ~


```

**Comment by dc8291** [comment]
Not sure if you are still having this problem, but I think you need to install Tensorflow and then run the setup.py.
